/// <reference types="cypress"/>
import '../../support/commands';

describe('Page d\'un fichier - Valider les panneaux masquables', () => {
  const setupTest = () => {
    cy.login();
    cy.visitFileEntity('FI0009813');
  };

  it('Panneau Summary', () => {
    setupTest();
    cy.get('[id="summary"] div[class*="ant-collapse-content-active"]').should('exist');
    cy.get('[id="summary"] span[class*="ant-collapse-arrow"]').clickAndWait({force: true});
    cy.get('[id="summary"] div[class*="ant-collapse-content-inactive ant-collapse-content-hidden"]').should('exist');
    cy.get('[id="summary"] span[class*="ant-collapse-arrow"]').clickAndWait({force: true});
    cy.get('[id="summary"] div[class*="ant-collapse-content-active"]').should('exist');
  });

  it('Panneau Data Type', () => {
    setupTest();
    cy.get('[id="data_type"] div[class*="ant-collapse-content-active"]').should('exist');
    cy.get('[id="data_type"] span[class*="ant-collapse-arrow"]').clickAndWait({force: true});
    cy.get('[id="data_type"] div[class*="ant-collapse-content-inactive ant-collapse-content-hidden"]').should('exist');
    cy.get('[id="data_type"] span[class*="ant-collapse-arrow"]').clickAndWait({force: true});
    cy.get('[id="data_type"] div[class*="ant-collapse-content-active"]').should('exist');
  });

  it('Panneau Participants-Samples', () => {
    setupTest();
    cy.get('[id="biospecimens"] div[class*="ant-collapse-content-active"]').should('exist');
    cy.get('[id="biospecimens"] span[class*="ant-collapse-arrow"]').clickAndWait({force: true});
    cy.get('[id="biospecimens"] div[class*="ant-collapse-content-inactive ant-collapse-content-hidden"]').should('exist');
    cy.get('[id="biospecimens"] span[class*="ant-collapse-arrow"]').clickAndWait({force: true});
    cy.get('[id="biospecimens"] div[class*="ant-collapse-content-active"]').should('exist');
  });

  it('Panneau Experimental Procedure', () => {
    setupTest();
    cy.get('[id="experimental_procedure"] div[class*="ant-collapse-content-active"]').should('exist');
    cy.get('[id="experimental_procedure"] span[class*="ant-collapse-arrow"]').clickAndWait({force: true});
    cy.get('[id="experimental_procedure"] div[class*="ant-collapse-content-inactive ant-collapse-content-hidden"]').should('exist');
    cy.get('[id="experimental_procedure"] span[class*="ant-collapse-arrow"]').clickAndWait({force: true});
    cy.get('[id="experimental_procedure"] div[class*="ant-collapse-content-active"]').should('exist');
  });

  it('Panneau Analysis Properties', () => {
    setupTest();
    cy.get('[id="analysis"] div[class*="ant-collapse-content-active"]').should('exist');
    cy.get('[id="analysis"] span[class*="ant-collapse-arrow"]').clickAndWait({force: true});
    cy.get('[id="analysis"] div[class*="ant-collapse-content-inactive ant-collapse-content-hidden"]').should('exist');
    cy.get('[id="analysis"] span[class*="ant-collapse-arrow"]').clickAndWait({force: true});
    cy.get('[id="analysis"] div[class*="ant-collapse-content-active"]').should('exist');
  });

  it('Panneau Files Generated by the Analysis', () => {
    setupTest();
    cy.get('[id="analysis_files"] div[class*="ant-collapse-content-active"]').should('exist');
    cy.get('[id="analysis_files"] span[class*="ant-collapse-arrow"]').clickAndWait({force: true});
    cy.get('[id="analysis_files"] div[class*="ant-collapse-content-inactive ant-collapse-content-hidden"]').should('exist');
    cy.get('[id="analysis_files"] span[class*="ant-collapse-arrow"]').clickAndWait({force: true});
    cy.get('[id="analysis_files"] div[class*="ant-collapse-content-active"]').should('exist');
  });
});
