/// <reference types="cypress"/>
import { oneMinute } from '../../pom/shared/Utils';
import '../../support/commands';

describe('Page d\'un fichier - Valider les liens disponibles', () => {
  const setupTest = () => {
    cy.login();
    cy.visitFileEntity('FH0003480');
  };

  it('Lien DataExploration du panneau Participants-Samples', () => {
    setupTest();
    cy.get('[id="biospecimens"] a[class*="EntityTableRedirectLink"]').clickAndWait({force: true});
    cy.get('[data-cy="ProTable_Participants"]', {timeout: oneMinute}).should('exist');
    cy.get('[class*="QueryBar_selected"] [class*="QueryPill_field"]').contains('File ID').should('exist');
    cy.get('[class*="QueryBar_selected"] [class*="QueryValues_value"]').contains('FH0003480').should('exist');
  });

  it('Lien Participant du panneau Participants-Samples', () => {
    setupTest();
    cy.get('[id="biospecimens"] td[class="ant-table-cell"]').eq(0).find('[href]').clickAndWait({force: true});
    cy.get('[id="participant-entity-page"]').should('exist');
    cy.get('[class*="EntityTitle"]').contains('PT0000964');
  });

  it('Lien Study du panneau Participants-Samples', () => {
    setupTest();
    cy.get('[id="biospecimens"] td[class="ant-table-cell"]').eq(1).find('[href]').clickAndWait({force: true});
    cy.get('[id="study-entity-page"]').should('exist');
    cy.get('[class*="EntityTitle"]').contains('Developmental and epileptic encephalopathies');
  });

  it('Lien NCIT du Sample Type du panneau Participants-Samples', () => {
    setupTest();
    cy.get('[id="biospecimens"] td[class="ant-table-cell"]').eq(3).find('[href]')
      .should('have.attr', 'href', 'http://purl.obolibrary.org/obo/NCIT_C449');
  });

  it('Lien NCIT du Tissue du panneau Participants-Samples', () => {
    setupTest();
    cy.get('[id="biospecimens"] td[class="ant-table-cell"]').eq(5).find('[href]')
      .should('have.attr', 'href', 'http://purl.obolibrary.org/obo/NCIT_C12434');
  });

  it('Lien DataExploration du panneau Files Generated by the Analysis', () => {
    setupTest();
    cy.get('[id="analysis_files"] a[class*="EntityTableRedirectLink"]').clickAndWait({force: true});
    cy.get('[data-cy="ProTable_DataFiles"]', {timeout: oneMinute}).should('exist');
    cy.get('[class*="QueryBar_selected"] [class*="QueryPill_field"]').contains('Analysis ID').should('exist');
    cy.get('[class*="QueryBar_selected"] [class*="QueryValues_value"]').contains('AN0001563').should('exist');
  });

  it('Lien File du panneau Files Generated by the Analysis', () => {
    setupTest();
    cy.get('[id="analysis_files"] [data-cy="Link_File_FH0004562"]').clickAndWait({force: true});
    cy.get('[id="file-entity-page"]').should('exist');
    cy.get('[class*="EntityTitle"]').contains('FH0004562');
  });
});
