groups:
  - name: portal-ui-cypress
    jobs:
      - run-cypress-tests-parallel  

resource_types:
- name: time
  type: registry-image
  source:
    repository: concourse/time-resource
    
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    username: ((docker.username))
    password: ((docker.password))
    tag: latest

resources:
# Cypress
- name: daily-schedule
  type: time
  check_every: 30s
  source:
    interval: 24h
    start: "09:00 AM"
    stop: "04:30 AM"
    location: "America/Toronto"
    days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]

- name: slack-alert-cypress
  type: slack-notification
  source:
    url: ((slack.webhook-url-cypress))

- name: ceph-storage
  type: s3
  source:
    endpoint: https://objets.juno.calculquebec.ca
    bucket: cqdg-qa-cypress-tests
    access_key_id: "((ceph.access_key))"
    secret_access_key: ((ceph.secret_key))
    use_ssl: false  # Set to true if ceph is configured with SSL
    regexp: test-results/merged-results-.*\.xml
   

- name: git-portal-ui
  type: git
  icon: github
  check_every: 5s
  webhook_token: ((slack.webhook-url))
  source:
    uri: git@github.com:Ferlab-Ste-Justine/cqdg-portal-ui.git
    branch: main
    private_key: ((git.ssh-key))
    # ignore_paths: [ci/]

- name: ci-folder
  type: git
  check_every: 30s
  source:
    uri: git@github.com:Ferlab-Ste-Justine/cqdg-portal-ui.git
    branch: main
    paths: [ci]
    private_key: ((git.ssh-key))

- name: open-pull-request
  type: pull-request
  check_every: 5s
  webhook_token: ((webhook-token))
  source:
    base_branch: main
    repository: Ferlab-Ste-Justine/cqdg-portal-ui
    access_token: ((git.access-token))
    states: ["OPEN"]
    # labels: ["bug"]

- name: closed-pull-request
  type: pull-request
  check_every: 5s
  webhook_token: ((webhook-token))
  source:
    base_branch: main
    repository: Ferlab-Ste-Justine/cqdg-portal-ui
    access_token: ((git.access-token))
    states: ["CLOSED", "MERGED"]

- name: ferlease
  type: docker-image
  icon: docker
  check_every: 30s
  source:
    username: ((docker.username))
    password: ((docker.password))
    repository: ferlabcrsj/ferlease
    tag: 0.2.2

jobs:
# Cypress
- name: run-cypress-tests-parallel
  plan:
  - get: daily-schedule
    trigger: true
  - get: git-portal-ui
    trigger: false
    params:
      submodule_recursive: true

  - in_parallel:
      fail_fast: false
      steps:

      - task: cypress-parallel-1
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ferlabcrsj/cypress-included-custom
              tag: latest
          inputs:
            - name: git-portal-ui
          outputs:
            - name: test-results-1
          params:
            CYPRESS_PASSWORD: ((cypress.password))
          run:
            path: bash
            args:
              - -c
              - |
                set +e 
                pushd git-portal-ui
                npm install
                cp env-qa .env
                sed -i 's/CYPRESS_PASSWORD=""/CYPRESS_PASSWORD="'$CYPRESS_PASSWORD'"/' .env
                npx cypress run --config-file cypress.config.ts --config retries=9 --browser chrome --reporter junit --reporter-options "mochaFile=../test-results-1/results-[hash].xml" --spec "cypress/e2e/Colonnes/*,cypress/e2e/Consultation/L*,cypress/e2e/Requetes/*,cypress/e2e/UploadList/*"
                
                # Run only the first Cypress test
                # FIRST_TEST=$(ls cypress/e2e/**/*.cy.{js,jsx,ts,tsx} | head -n 1)
                # npx cypress run --config-file cypress.config.ts --config retries=2 --browser chrome --reporter junit --reporter-options "mochaFile=../test-results-1/results-[hash].xml" --spec "$FIRST_TEST"
             
                popd
                exit 0

      - task: cypress-parallel-2
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ferlabcrsj/cypress-included-custom
              tag: latest
          inputs:
            - name: git-portal-ui
          outputs:
            - name: test-results-2
          params:
            CYPRESS_PASSWORD: ((cypress.password))
          run:
            path: bash
            args:
              - -c
              - |
                set +e 
                pushd git-portal-ui
                npm install
                cp env-qa .env
                sed -i 's/CYPRESS_PASSWORD=""/CYPRESS_PASSWORD="'$CYPRESS_PASSWORD'"/' .env
                npx cypress run --config-file cypress.config.ts --config retries=9 --browser chrome --reporter junit --reporter-options "mochaFile=../test-results-2/results-[hash].xml" --spec "cypress/e2e/Navigation/*,cypress/e2e/Consultation/P*"
                
                # Run only the first Cypress test
                # FIRST_TEST=$(ls cypress/e2e/**/*.cy.{js,jsx,ts,tsx} | head -n 1)
                # npx cypress run --config-file cypress.config.ts --config retries=2 --browser chrome --reporter junit --reporter-options "mochaFile=../test-results-2/results-[hash].xml" --spec "$FIRST_TEST"
             
                popd
                exit 0
      - task: cypress-parallel-3
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ferlabcrsj/cypress-included-custom
              tag: latest
          inputs:
            - name: git-portal-ui
          outputs:
            - name: test-results-3
          params:
            CYPRESS_PASSWORD: ((cypress.password))
          run:
            path: bash
            args:
              - -c
              - |
                set +e 
                pushd git-portal-ui
                npm install
                cp env-qa .env
                sed -i 's/CYPRESS_PASSWORD=""/CYPRESS_PASSWORD="'$CYPRESS_PASSWORD'"/' .env
                npx cypress run --config-file cypress.config.ts --config retries=9 --browser chrome --reporter junit --reporter-options "mochaFile=../test-results-3/results-[hash].xml" --spec "cypress/e2e/Facettes/*"

                # Run only the first Cypress test
                # FIRST_TEST=$(ls cypress/e2e/**/*.cy.{js,jsx,ts,tsx} | head -n 1)
                # npx cypress run --config-file cypress.config.ts --config retries=2 --browser chrome --reporter junit --reporter-options "mochaFile=../test-results-3/results-[hash].xml" --spec "$FIRST_TEST"
             
                popd
                exit 0
      - task: cypress-parallel-4
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ferlabcrsj/cypress-included-custom
              tag: latest
          inputs:
            - name: git-portal-ui
          outputs:
            - name: test-results-4
          params:
            CYPRESS_PASSWORD: ((cypress.password))
          run:
            path: bash
            args:
              - -c
              - |
                set +e
                pushd git-portal-ui
                npm install
                cp env-qa .env
                sed -i 's/CYPRESS_PASSWORD=""/CYPRESS_PASSWORD="'$CYPRESS_PASSWORD'"/' .env
                npx cypress run --config-file cypress.config.ts --config retries=9 --browser chrome --reporter junit --reporter-options "mochaFile=../test-results-4/results-[hash].xml" --spec "cypress/e2e/Telechargement/*,cypress/e2e/Consultation/T*"

                # Run only the first Cypress test
                # FIRST_TEST=$(ls cypress/e2e/**/*.cy.{js,jsx,ts,tsx} | head -n 1)
                # npx cypress run --config-file cypress.config.ts --config retries=2 --browser chrome --reporter junit --reporter-options "mochaFile=../test-results-4/results-[hash].xml" --spec "$FIRST_TEST"
             
                popd
                exit 0
                
  - task: merge-results
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ferlabcrsj/cypress-included-custom
          tag: latest
      inputs:
        - name: test-results-1
        - name: test-results-2
        - name: test-results-3
        - name: test-results-4
      outputs:
        - name: merged-results
        - name: timestamp
      run:
        path: bash
        args:
          - -c
          - |
            set -e # Exit on error
            mkdir -p merged-results
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            echo $TIMESTAMP > timestamp/timestamp.txt
            npx junit-merge test-results-1/*.xml test-results-2/*.xml test-results-3/*.xml test-results-4/*.xml -o merged-results/merged-results-${TIMESTAMP}.xml

  - put: ceph-storage
    params:
      file: merged-results/merged-results-*.xml
    no_get: true

  - task: generate-presigned-url
    params:
      CEPH_ACCESS_KEY: ((ceph.access_key))
      CEPH_SECRET_KEY: ((ceph.secret_key))
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ferlabcrsj/cypress-included-custom
          tag: latest
      inputs:
        - name: merged-results
        - name: timestamp
      outputs:
        - name: slack-data
      run:
        path: bash
        args:
          - -c
          - |
            set -e  # Exit on error

            # Read the timestamp
            TIMESTAMP=$(cat timestamp/timestamp.txt)

            # Check if the merged results file is not empty
            if [ -s merged-results/merged-results-${TIMESTAMP}.xml ]; then
              # Generate a pre-signed URL
              mc alias set myceph https://objets.juno.calculquebec.ca $ceph_ACCESS_KEY $MINIO_SECRET_KEY
              PRESIGNED_URL=$(mc share download myminio/cqgc-qa-cypress-tests/test-results/merged-results-${TIMESTAMP}.xml --expire=48h | grep -oP '(?<=Share: ).*')

              # Prepare Slack message for success
              echo '[
                {
                  "color": "good",
                  "title": "Portal UI Cypress Test Results",
                  "text": "Cypress test results are available for Portal UI. <'$PRESIGNED_URL'|View Results>"
                }
              ]' > slack-data/attachments.json
            else
              # Prepare Slack message for absence of results
              echo '[
                {
                  "color": "warning",
                  "title": "Portal UI Cypress Test Results",
                  "text": "No test results are available for Portal UI due to an error or no tests were executed."
                }
              ]' > slack-data/attachments.json
            fi

  - put: slack-alert-cypress
    params:
      attachments_file: slack-data/attachments.json




